bookyardApp/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from bookyardApp.db import get_db
import bookyardApp.models as models

authbp = Blueprint('auth', __name__, url_prefix='/auth')

# Register Page
@authbp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif models.selectUser(username, db) is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            models.addUser(username, generate_password_hash(password), db)
            session.clear()
            session['user_id'] = models.selectUser(username, db)['id']
            return redirect(url_for('views.index'))

        flash(error)

    return render_template('register.html')

# Login Page
@authbp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = models.selectUser(username, db)

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('views.index'))

        flash(error)

    return render_template('login.html')

# Logout Page
@authbp.route('/logout')
def logout():
    g.user = None
    session.clear()
    return redirect(url_for('views.index'))

@authbp.route('/save_preference')
def save_preference():
    return '..'


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

@authbp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = user_id

bookyardApp/views.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from bookyardApp.db import get_db
import bookyardApp.models as models
from bookyardApp.auth import login_required

viewsbp = Blueprint('views', __name__)

# Homepage
@viewsbp.route('/')
@login_required
def index():
    db = get_db()
    books = models.getBooksbyUser(db, g.user)
    return render_template('index.html', books=books)

@viewsbp.route('/search_book/<prefix>', methods=('GET', 'POST'))
@login_required
def search_book(prefix='a'):
    db = get_db()
    books = models.searchBook(prefix, db, g.user)[:100]
    if request.method == 'POST':
        if request.form['name'] == 'bookSearch':
            prefix = request.form['bookSearch']
            return redirect(url_for('views.search_book', prefix=prefix))
        elif request.form['name'] == 'bookPreference':
            bookId = request.form['bookId']
            rating = request.form['rating']
            inst = models.searchRatingIns(db, g.user, bookId)
            if inst is not None:
                if inst['rating'] != rating:
                    models.deleteRating(db, g.user, bookId)
                    models.addRating(db, g.user, bookId, rating)
            else:
                models.addRating(db, g.user, bookId, rating)

            return redirect(request.referrer)

    return render_template('search_book.html', books=books)


@viewsbp.route('/recommend_book', methods=('GET', 'POST'))
@login_required
def recommend_book():
    user_id = session.get('user_id')
    db = get_db()
    liked_bookId = db.execute(
        'SELECT * FROM rating WHERE rating > 5 AND userid = ?', (user_id,)
    )
    op = models.Operation(get_db())
    books = op.recommend(user_id, 1800, 9)
    if request.method == 'GET':
        return render_template('recommend.html', books=books, liked_bookId=liked_bookId)
    elif request.method == 'POST':
        bookId = request.form['bookId']
        like = request.form['preference']
        # print("books******************************************")
        # print(bookId)
        # print(like)
        if like == "like":
            # print("I am in like")
            # print("books******************************************")
            # print(models.selectBook(db, bookId)['title'])
            models.deleteRating(db, g.user, bookId)
            models.addRating(db, g.user, bookId, rating=6)
            flash("You Like {}.".format(models.selectBook(db, bookId)['title']))
        else:
            # print("I am in un-like")
            models.deleteRating(db, g.user, bookId)
            flash("You don't like {}.".format(models.selectBook(db, bookId)['title']))
        return render_template('recommend.html', books=books, liked_bookId=liked_bookId)


def save_preference():
    db = get_db()
    bookId = request.form['bookId']
    like = request.form['preference']
    # print("books******************************************")
    # print(bookId)
    # print(like)
    if request.method == 'POST':
        if like == "like":
            print("I am in like")
            models.deleteRating(db, g.user, bookId)
            models.addRating(db, g.user, bookId, rating=6)
            print("books******************************************")
            print(models.selectBook(db, bookId)['title'])
            flash("You Like {}.".format(models.selectBook(db, bookId)['title']))
        else:
            print("I am in un-like")
            models.deleteRating(db, g.user, bookId)
            flash("You don't like {}.".format(models.selectBook(db, bookId)['title']))
    return recommend_book()

bookyardApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Bookyard</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="static/css/base.css" rel="stylesheet">
	</head>

	<body>
        {#    navbar#}
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('views.index') }}">Bookyard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
{#                        {% if true %}#}
                        {% if g.user != None %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('views.search_book', prefix='a') }}">Search</a>
                            </li>
{#                            <li class="nav-item">#}
{#                                <a class="nav-link" href="{{ url_for('views.top_books') }}">Top Books</a>#}
{#                            </li>#}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('views.recommend_book') }}">You May Like</a>
                            </li>
                        {% else %}
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if g.user != None %}
{#                        {% if false %}#}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
			{% for message in get_flashed_messages() %}
			<div class="alert alert-primary" role="alert">
				{{ message }}
			</div>
			{% endfor %}

			{% block body %}{% endblock %}
		</div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		</body>
</html>

bookyardApp/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h2>Your Books</h2>

{#    card desk#}
<div class="card-columns">
{% for book in books[:100] %}
  <div class="card">
    <img src="{{ book['img_url_l'] }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ book['title'] }}</h5>
        <form class="form-inline" method="post">
        <div class="form-group mx-sm-3 mb-2">
          {% if book['rating'] != None %}
          <input type="number" min="1" max="10" class="form-control" name="rating" id="rating" value="{{ book['rating'] }}" required>
          {% else %}
          <input type="number" min="1" max="10" class="form-control" name="rating" id="rating" placeholder="1-10" required>
          {% endif %}
            <input type="hidden" value={{ book['bookId'] }} name="bookId">
            <input type="hidden" name="name" value="bookPreference">
        </div>
            <button type="submit" class="btn btn-primary mb-2">Rate</button>
        </form>
    </div>
   </div>
{% endfor %}

</div>

{% endblock %}

bookyardApp/templates/login.html
{% extends 'base.html' %}

{% block body %}
    <h2>Log In</h2>
    <form method="post">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
      </div>
    {#  <div class="form-group form-check">#}
    {#    <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
    {#    <label class="form-check-label" for="exampleCheck1">Check me out</label>#}
    {#  </div>#}
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

bookyardApp/templates/recommend.html
{% extends 'base.html' %}

{% block body %}
    <h2>You may like</h2>

{#    card dest#}

<div class="card-columns">
{% for book in books[:100] %}
  <div class="card">
    <img src="{{ book['img_url_l'] }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ book['title'] }}</h5>
        <form class="form-inline" method="post">
    {% if book['isbn'] not in liked_bookId %}
{#        <a href="#" class="btn btn-primary">Go somewhere</a>#}
        <input type="hidden" name="preference" value="like">
            <input type="hidden" value={{book['bookId']}} name = "bookId">
        <button type="submit" formmethod="post" class="btn btn-primary">Like</button>
    {% else %}
        <input type="hidden" name="preference" value="unlike">
        <button type="submit" formmethod="post" class="btn btn-primary">Un-Like</button>
    {% endif %}
        </form>
    </div>
   </div>
{% endfor %}

</div>

{% endblock %}

bookyardApp/templates/register.html
{% extends 'base.html' %}

{% block body %}
    <h2>Get an Account</h2>
    <form method="post">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
      </div>
    {#  <div class="form-group form-check">#}
    {#    <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
    {#    <label class="form-check-label" for="exampleCheck1">Check me out</label>#}
    {#  </div>#}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

bookyardApp/templates/search_book.html
{% extends 'base.html' %}

{% block body %}
    <h2>Loop up book</h2>
<!-- Search form -->
    <form method="post" name="searchBar" id="searchBar">
     <div class="form-group row">
        <label for="bookSearch" class="col-sm-2 col-form-label">Search Book</label>
        <div class="col-sm-10">
          <input type="hidden" name="name" value="bookSearch">
          <input type="text" class="form-control" name="bookSearch" id="bookSearch" placeholder="Search" required>
        </div>
      </div>
    </form>

{% if books|length == 0 %}
<div>
<h4> </h4>
<h4>Didn't find the book...</h4>
</div>
{% else %}
{#    card desk#}
<div class="card-columns">
{% for book in books %}
  <div class="card">
    <img src="{{ book['img_url_l'] }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ book['title'] }}</h5>
        <form class="form-inline" method="post">
        <div class="form-group mx-sm-3 mb-2">
          {% if book['rating'] != None %}
          <input type="number" min="1" max="10" class="form-control" name="rating" id="rating" value="{{ book['rating'] }}" required>
          {% else %}
          <input type="number" min="1" max="10" class="form-control" name="rating" id="rating" placeholder="1-10" required>
          {% endif %}
            <input type="hidden" value={{ book['bookId'] }} name="bookId">
            <input type="hidden" name="name" value="bookPreference">
        </div>
            <button type="submit" class="btn btn-primary mb-2">Rate</button>
        </form>
    </div>
   </div>
{% endfor %}

</div>
{% endif %}
{% endblock %}