webserver_legacy/app/models.py
from app import db
from sqlalchemy.dialects.mysql import INTEGER
from sqlalchemy import func, desc, select
from werkzeug.security import generate_password_hash, check_password_hash
import numpy as np

class User(db.Model):
	__tablename__ = "users"

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	email = db.Column(db.String(60), index=True, unique=True)
	password = db.Column(db.String(128))
	age = db.Column(db.Integer)
	location = db.Column(db.String(250))
	authenticated = db.Column(db.Boolean, default=False)

	ratings = db.relationship("Rating")

	def set_password(self, password):
		self.password = generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password, password)

	@property
	def is_authenticated(self):
		"""Return True if the user is authenticated."""
		return self.authenticated

	@property
	def is_active(self):
		"""Always True, as all users are active."""
		return True

	@property
	def is_anonymous(self):
		"""Always False, as anonymous users aren't supported."""
		return False

	def get_id(self):
		"""Return the email address to satisfy Flask-Login's requirements."""
		return str(self.id)

	def __repr__(self):
		return "User {}".format(self.id)

	def __str__(self):
		return self.__repr__()

class Book(db.Model):
	__tablename__ = "books"

	isbn = db.Column(db.String(13), primary_key=True)
	title = db.Column(db.String(255))
	author = db.Column(db.String(255))
	year_of_pub = db.Column(INTEGER(unsigned=True))
	publisher = db.Column(db.String(255))
	img_url_s = db.Column(db.String(255))
	img_url_m = db.Column(db.String(255))
	img_url_l = db.Column(db.String(255))

	def __repr__(self):
		return "Book {}".format(self.isbn)

	def __str__(self):
		return self.__repr__()

class Rating(db.Model):
	__tablename__ = "ratings"

	uid = db.Column(db.Integer, db.ForeignKey("users.id"), primary_key=True)
	isbn = db.Column(db.String(13), db.ForeignKey("books.isbn"), primary_key=True)
	rating = db.Column(db.Integer)

	def __repr__(self):
		return "Rating {}".format(self.isbn + ", " + str(self.uid))

	def __str__(self):
		return self.__repr__()

class Recommender(object):
	# def __init__(self):
	# 	with open("recsys/explicit_rec.pkl", "rb") as fid:
	# 		self.model = pickle.load(fid)

	def most_rated(self, n=3):
		queried_books = db.session.query(Rating.isbn, func.count(Rating.rating).label('qty')).group_by(Rating.isbn).order_by(desc('qty')).limit(n).all()
		books = []
		for book in queried_books:
			books.append(Book.query.get(book[0]))

		return books

	def top_average_rated(self, n=3):
		queried_books = db.session.query(Rating.isbn,
				func.count(Rating.rating).label('qty'),
				func.avg(Rating.rating).label('avg_rating')
				).group_by(Rating.isbn).order_by(desc('avg_rating'), desc('qty')).limit(n).all()

		books = []
		for book in queried_books:
			books.append(Book.query.get(book[0]))

		return books

	def top_rated(self, n=3):
		queried_books = db.session.query(Rating.isbn, Rating.rating.label('rating')).order_by(desc('rating')).limit(n).all()

		books = []
		for book in queried_books:
			books.append(Book.query.get(book[0]))

		return books

	def top_rated_isbns(self, n=3):
		queried_books = db.session.query(Rating.isbn, Rating.rating.label('rating')).order_by(desc('rating')).limit(n).all()

		books = []
		for book in queried_books:
			books.append(book[0])

		return books

	def recommend(self, n=3):
		queried_books = [b.isbn for b in db.session.query(Book.isbn)]
		queried_books = np.random.choice(queried_books, n, replace=False)

		books = []
		for isbn in queried_books:
			books.append(Book.query.get(isbn))

		return books

webserver_legacy/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()

login_manager = LoginManager()

def create_app(config_name):
	app = Flask(__name__, instance_relative_config=True)
	app.config.from_object(app_config[config_name])
	app.config.from_pyfile("config.py")
	app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://<hostname>:<password>@localhost/bookyard"
	app.secret_key = "secret_key"

	login_manager.init_app(app)
	login_manager.login_view = "auth.login"

	from app import models
	with app.app_context():
		db.init_app(app)
		db.create_all()
		db.session.commit()

	@login_manager.user_loader
	def load_user(user_id):
		return models.User.query.get(user_id)

	from .home import home as home_blueprint
	app.register_blueprint(home_blueprint)

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint)

	return app

webserver_legacy/app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

from . import views

webserver_legacy/app/home/views.py
from flask import Flask, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required
from string import ascii_uppercase
import numpy as np
from app import models
from . import home

@home.route("/")
def index():
	return render_template("home/index.html")

@home.route("/book-lookup/<letter>")
@login_required
def book_lookup(letter="a"):
	letter = letter.upper()[0]
	books = models.Book.query.filter(models.Book.title.startswith(letter)).all()
	if books is not None:
		liked_isbns = []
		for rating in current_user.ratings:
			liked_isbns.append(rating.isbn)

		return render_template("home/lookup.html", letter=letter, books=books, liked_isbns=liked_isbns, ascii_upper=list(ascii_uppercase))
	else:
		flash("Please search for a valid book entry.")
		return redirect(url_for("home.book_lookup"))

@home.route("/book/<isbn>")
@login_required
def render_book(isbn):
	book = models.Book.query.filter_by(isbn=isbn).first()

	if book is not None:
		return render_template("home/book.html", book=book)
	else:
		flash("Book does not exist.")
		return redirect(url_for("home.book_lookup"))

@home.route("/top-books")
@login_required
def top_books():
	rec = models.Recommender()
	return render_template("home/top_books.html", rated=rec.top_average_rated(), trending=rec.most_rated())

@home.route("/recommended")
@login_required
def recommend():
	rec = models.Recommender()
	return render_template("home/recommended.html", recommended=rec.recommend())

webserver_legacy/app/templates/helpers/_form_helpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field(**kwargs)|safe }}
	{% if field.errors %}
		<ul class=errors>
			{% for error in field.errors %}
				<li>{{ error }}</li>
			{% endfor %}
		</ul>
	{% endif %}
</dd>
{% endmacro %}

webserver_legacy/app/templates/home/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Unauthorized Access:: Python Flask Bucket List App</title>

   
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link href="../static/css/signup.css" rel="stylesheet">
    
   
  </head>

  <body>

    <div class="container">
      <div class="header">
        <nav>
           <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="/showSignin">Sign In</a></li>
 	    <li role="presentation"><a href="/showSignUp">Sign Up</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Python Flask App</h3>
      </div>

      <div class="jumbotron">
        <h1>{{error}}</h1>
        
      </div>

      

      <footer class="footer">
        <p>&copy; Company 2015</p>
      </footer>

    </div>
  </body>
</html>

webserver_legacy/app/templates/home/index.html
{% extends 'layout.html' %}

{% block body %}

<div class="index">
	<div class="jumbotron">
		<div class="col-lg-12">
			<h1>Bookyard</h1>
		</div>
	</div>
</div>
{% endblock %}

webserver_legacy/app/templates/home/lookup.html
{% extends 'layout.html' %}

{% block body %}

<nav class="lookup-breadcrumb" aria-label="breadcrumb" role="navigation">
	<ol class="breadcrumb">
			{% for c in ascii_upper %}
				{% if c == letter %}
					<li class="breadcrumb-item active" aria-current="page">{{ c }}</li>
				{% else %}
					<li class="breadcrumb-item"><a href="{{ url_for('home.book_lookup', letter=c) }}">{{ c }}</a></li>
				{% endif %}
			{% endfor %}
	</ol>
</nav>

<div class="row">
{% for book in books[:100] %}
	<div class="col-sm-4">
		<div class="card">
			<div class="card-header">
    			<h4 class="card-title">{{ book.title }}</h4>
  			</div>
			<img class="card-img-top" src="{{ book.img_url_l }}" />
			<div class="card-body text-center">
				<h6 class="card-text">By {{ book.author }}</h6>
				<form action="{{ url_for('auth.save_preference', uid=current_user.id) }}" method="post">
					<input type="hidden" name="uid" value="{{ current_user.id }}">
					<input type="hidden" name="isbn" value="{{ book.isbn }}">

					{% if book.isbn not in liked_isbns %}
						<input type="hidden" name="preference" value="like">
						<button type="submit" formmethod="post" class="btn btn-primary">Like</button>
					{% else %}
						<input type="hidden" name="preference" value="unlike">
						<button type="submit" formmethod="post" class="btn btn-primary">Un-Like</button>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
{% endfor %}
</div>

{% endblock %}

webserver_legacy/app/templates/home/recommended.html
{% extends 'layout.html' %}

{% block body %}

<div class="row">
{% for book in recommended %}
	<div class="col-sm-4">
		<div class="card">
			<div class="card-header">
    			<h4 class="card-title">{{ book.title }}</h4>
  			</div>
			<img class="card-img-top" src="{{ book.img_url_m }}" />
			<div class="card-body text-center">
				<h6 class="card-text">By {{ book.author }}</h6>
				<form action="{{ url_for('auth.save_preference', uid=current_user.id) }}" method="post">
					<input type="hidden" name="uid" value="{{ current_user.id }}">
					<input type="hidden" name="isbn" value="{{ book.isbn }}">

					{% if book.isbn not in liked_isbns %}
						<input type="hidden" name="preference" value="like">
						<button type="submit" formmethod="post" class="btn btn-primary">Like</button>
					{% else %}
						<input type="hidden" name="preference" value="unlike">
						<button type="submit" formmethod="post" class="btn btn-primary">Un-Like</button>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
{% endfor %}
</div>

{% endblock %}

webserver_legacy/app/templates/home/top_books.html
{% extends 'layout.html' %}

{% block body %}

<h1>Trending Books</h1>
<div class="row">
{% for book in trending %}
	<div class="col-sm-4">
		<div class="card">
			<div class="card-header">
    			<h4 class="card-title">{{ book.title }}</h4>
  			</div>
			<img class="card-img-top" src="{{ book.img_url_m }}" />
			<div class="card-body text-center">
				<h6 class="card-text">By {{ book.author }}</h6>
				<form action="{{ url_for('auth.save_preference', uid=current_user.id) }}" method="post">
					<input type="hidden" name="uid" value="{{ current_user.id }}">
					<input type="hidden" name="isbn" value="{{ book.isbn }}">

					{% if book.isbn not in liked_isbns %}
						<input type="hidden" name="preference" value="like">
						<button type="submit" formmethod="post" class="btn btn-primary">Like</button>
					{% else %}
						<input type="hidden" name="preference" value="unlike">
						<button type="submit" formmethod="post" class="btn btn-primary">Un-Like</button>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
{% endfor %}
</div>

<h1>Highest Rated Books</h1>
<div class="row">
{% for book in rated %}
	<div class="col-sm-4">
		<div class="card">
			<div class="card-header">
    			<h4 class="card-title">{{ book.title }}</h4>
  			</div>
			<img class="card-img-top" src="{{ book.img_url_m }}" />
			<div class="card-body text-center">
				<h6 class="card-text">By {{ book.author }}</h6>
				<form action="{{ url_for('auth.save_preference', uid=current_user.id) }}" method="post">
					<input type="hidden" name="uid" value="{{ current_user.id }}">
					<input type="hidden" name="isbn" value="{{ book.isbn }}">

					{% if book.isbn not in liked_isbns %}
						<input type="hidden" name="preference" value="like">
						<button type="submit" formmethod="post" class="btn btn-primary">Like</button>
					{% else %}
						<input type="hidden" name="preference" value="unlike">
						<button type="submit" formmethod="post" class="btn btn-primary">Un-Like</button>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
{% endfor %}
</div>

{% endblock %}

webserver_legacy/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Bookyard</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
		<link href="/static/main.css" rel="stylesheet">
	</head>

	<body>
		{% include 'partials/_header.html' %}

		<div class="container">
			{% for message in get_flashed_messages() %}
			<div class="alert alert-primary" role="alert">
				{{ message }}
			</div>
			{% endfor %}

			{% block body %}{% endblock %}
		</div>

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	</body>
</html>

webserver_legacy/app/templates/partials/_header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<a class="navbar-brand" href="{{ url_for('home.index') }}">Montag</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				{% if current_user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('home.book_lookup', letter='a') }}">Book Lookup</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('home.top_books') }}">Top Books</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('home.recommend') }}">Recommended For You</a>
					</li>
				{% else %}
				{% endif %}
			</ul>
			<ul class="navbar-nav">
				{% if current_user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>